from django import forms
from .models import Vendor

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = [
            'vendor_name',
            'vendor_type',
            'gst_no',
            'pan_no',
            'company_status',
            'state',
            'banking_name',
            'bank',
            'ifsc',
            'account_number',
            'address',
            'std_code_phone_no',
            'contact_person',
            'city',
            'fax',
            'contact_person_designation',
            'website',
            'is_msmse',
            'mobile',
            'business_description',
            'email',
            'pin',
        ]
        labels = {
            'vendor_name': 'Name of Firm/Company',
            'vendor_type': 'Type of Firm',
            'gst_no': 'GST No',
            'pan_no': 'PAN No',
            'company_status': 'Status of Company',
            'state': 'State',
            'banking_name': 'Vendor Banking Name',
            'bank': 'Vendor Bank',
            'ifsc': 'Vendor IFSC',
            'account_number': 'Vendor Account Number',
            'address': 'Address',
            'std_code_phone_no': 'STD Code with Phone No.',
            'contact_person': 'Name of Contact Person',
            'city': 'City',
            'fax': 'Fax',
            'contact_person_designation': 'Designation of Contact Person',
            'website': 'Website',
            'is_msmse': 'Is your Firm MSME?',
            'mobile': 'Mobile Number',
            'business_description': 'Brief Description of Business',
            'email': 'Email',
            'pin': 'PIN Code',
        }
        widgets = {
            'vendor_name': forms.TextInput(attrs={'class': 'form-control'}),
            'vendor_type': forms.Select(attrs={'class': 'form-control'}),
            'gst_no': forms.TextInput(attrs={'class': 'form-control'}),
            'pan_no': forms.TextInput(attrs={'class': 'form-control'}),
            'company_status': forms.Select(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'banking_name': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'ifsc': forms.TextInput(attrs={'class': 'form-control'}),
            'account_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'std_code_phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'contact_person': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'fax': forms.TextInput(attrs={'class': 'form-control'}),
            'contact_person_designation': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Enter Website URL (Optional)'}),
            'is_msmse': forms.Select(choices=[('Yes', 'Yes'), ('No', 'No')], attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'business_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'pin': forms.TextInput(attrs={'class': 'form-control'}),
        }
